<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>VeganLife</RootNamespace>
		<UseMaui>true</UseMaui>
		<MauiVersion>8.0.21</MauiVersion>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>HealthyChef</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.snailb.healthychef</ApplicationId>
		<ApplicationIdGuid>F4C59B5E-E230-4D45-85B2-8BF64759FFE1</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0.22</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion> -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>$(DefineConstants);DATACENTER;GPT</DefineConstants>
		<Optimize>True</Optimize>
		<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
		<LangVersion>latest</LangVersion>
		<WarningLevel>4</WarningLevel>
		<_MauiForceXamlCForDebug>False</_MauiForceXamlCForDebug>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
		<AndroidLinkTool>r8</AndroidLinkTool>
		<AndroidLinkMode>SdkOnly</AndroidLinkMode>
		<RunAOTCompilation>true</RunAOTCompilation>
		<AndroidPackageFormats>aab;apk</AndroidPackageFormats>
		<AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	</PropertyGroup>

	<!--<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
	  --><!--<AndroidEnableMultiDex>True</AndroidEnableMultiDex>--><!--
	</PropertyGroup>-->

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#a4a7ea" ForegroundScale="0.65" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#a4a7ea" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\facebook2019.svg" BaseSize="50,50" />
		<MauiImage Update="Resources\Images\google.svg" BaseSize="50,50" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<AndroidResource Remove="Models\Base\**" />
		<Compile Remove="Models\Base\**" />
		<EmbeddedResource Remove="Models\Base\**" />
		<MauiCss Remove="Models\Base\**" />
		<MauiXaml Remove="Models\Base\**" />
		<None Remove="Models\Base\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Views\LoginPage.xaml.cs" />
	  <Compile Remove="Views\RegistrationPage.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiAsset Remove="Resources\Raw\chat_detail.txt" />
	  <MauiAsset Remove="Resources\Raw\chat_disclaimer.txt" />
	  <MauiAsset Remove="Resources\Raw\tutorial.txt" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="Views\LoginPage.xaml" />
	  <MauiXaml Remove="Views\RegistrationPage.xaml" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="proguard.cfg" />
		<None Remove="Resources\Fonts\FontAwesome6FreeBrands.otf" />
		<None Remove="Resources\Fonts\FontAwesome6FreeRegular.otf" />
		<None Remove="Resources\Fonts\FontAwesome6FreeSolid.otf" />
		<None Remove="Resources\Images\facebook2019.svg" />
		<None Remove="Resources\Images\google.svg" />
		<None Remove="Resources\Images\microsoft.svg" />
		<None Remove="Resources\Images\nutrition_plan.svg" />
		<None Remove="Resources\Images\trending_fire.png" />
		<None Remove="Resources\Images\web_view.svg" />
		<None Remove="Resources\Raw\chat_detail.txt" />
		<None Remove="Resources\Raw\chat_disclaimer.txt" />
		<None Remove="Resources\Raw\empty_list.json" />
		<None Remove="Resources\Raw\loading.json" />
		<None Remove="Resources\Raw\mail_template.txt" />
		<None Remove="Resources\Raw\swipe_rightToLeft.json" />
		<None Remove="Resources\Raw\tutorial.txt" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\Raw\chat_detail.txt" />
	  <EmbeddedResource Include="Resources\Raw\chat_disclaimer.txt" />
	  <EmbeddedResource Include="Resources\Raw\tutorial.txt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.8" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.8" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.8" />
		<PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.8" />
		<PackageReference Include="CommunityToolkit.Maui" Version="9.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="akgul.Maui.DataGrid" Version="4.0.4" />
		<PackageReference Include="CardsView.Maui" Version="0.0.6" />
		<PackageReference Include="FFImageLoading.Maui" Version="1.2.3" />
		<PackageReference Include="FirebaseDatabase.net" Version="4.2.0" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc1" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
		<!--<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.3" />-->
		<PackageReference Include="Mopups" Version="1.3.1" />
		<PackageReference Include="Sharpnado.Tabs.Maui" Version="3.0.1" />
		<PackageReference Include="ChatGptNet" Version="3.2.14" />
		<PackageReference Include="SkiaSharp.Extended.UI.Maui" Version="2.0.0" />
		<PackageReference Include="Sharpnado.MaterialFrame.Maui" Version="2.0.0" />
		<PackageReference Include="Utf8Json" Version="1.3.7" />
		<PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
		<PackageReference Include="Sharpnado.CollectionView.Maui" Version="3.1.2" />
		<PackageReference Include="Sharpnado.TaskMonitor" Version="1.0.2" />
		<!--<PackageReference Include="Firebase.Auth" Version="1.0.0" />-->
		<!--<PackageReference Include="FirebaseAuthentication.net" Version="4.0.2" />-->
	</ItemGroup>

	<ItemGroup>
	  <ProguardConfiguration Include="proguard.cfg" />
	</ItemGroup>
	<!--<ItemGroup>
	  <ProjectReference Include="..\VeganLifeDataCenter\VeganLifeDataCenter.csproj" />
	</ItemGroup>-->
	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.5-beta1.23270.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MvvmCross.CodeAnalysis" Version="8.0.2" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Translations\AppResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AppResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Views\BookmarkPage.xaml.cs">
			<DependentUpon>BookmarkPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\NavBarControl.xaml.cs">
			<DependentUpon>NavBarControl.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\Tabs\MacrosPage.xaml.cs">
			<DependentUpon>MacrosPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\Tabs\MacrosPage.xaml.cs">
			<DependentUpon>MacrosPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\ToolFlyout\MainTool.xaml.cs">
			<DependentUpon>MainTool.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Translations\AppResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>AppResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<MauiXaml Update="Views\ChatFlyout\ChatGPTDetailPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChatFlyout\ChatGPTDisClaimerPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChatFlyout\ChatListPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ChatFlyout\ConversationPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\DataGridNutritionFactCW.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\NutritionFactsFoodDetail.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\RecipeFoodDetail.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\MaterialFrameSelectControl.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NutritionFactImportantBorder.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Templates\BotMessItemTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Templates\UserMessItemTemplate.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ToolFlyout\BMRCalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\BookmarkPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ToolFlyout\BMICalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\ElementFoodDetailCW.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\CaloriesTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\MacrosTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\NutrientsTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\VitaminAndMineralPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\FlyoutHeader.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NavBarControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NavBarRootPageControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\Tabs\CaloriesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\Tabs\MacrosPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\VitaminTab\DetailVitaminAndMineralPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\FoodTab\FoodDetailPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\FoodTab\FoodsByCategoryPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\NewsFeedPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\AboutAppPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\BmiMoreInfoToolBarPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\BmiResultPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\ProfilePopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\PortionTab\UsdaFoodFactDetailPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ProfilePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\MainPageFlyout\ReportPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SettingFlyout\SettingPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SettingFlyout\LicensePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ToolFlyout\BMICalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\WebViewPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\WelcomePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>
</Project>
