<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>VeganLife</RootNamespace>
		<UseMaui>true</UseMaui>
		<MauiVersion>8.0.3</MauiVersion>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>HealthyChef</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.snailb.healthychef</ApplicationId>
		<ApplicationIdGuid>F4C59B5E-E230-4D45-85B2-8BF64759FFE1</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0.5</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion> -->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DefineConstants>$(DefineConstants);DATACENTER;GPT</DefineConstants>
		<Optimize>True</Optimize>
		<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
		<LangVersion>latest</LangVersion>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-android|AnyCPU'">
		<!--<AndroidLinkTool>r8</AndroidLinkTool>-->
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
		<!--<AndroidLinkTool>r8</AndroidLinkTool>-->
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#a4a7ea" ForegroundScale="0.65" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#a4a7ea" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\facebook2019.svg" BaseSize="50,50" />
		<MauiImage Update="Resources\Images\google.svg" BaseSize="50,50" />
		<MauiImage Update="Resources\Images\filter.svg" BaseSize="25,25" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<AndroidResource Remove="Models\Base\**" />
		<AndroidResource Remove="Views\Templates\**" />
		<Compile Remove="Models\Base\**" />
		<Compile Remove="Views\Templates\**" />
		<EmbeddedResource Remove="Models\Base\**" />
		<EmbeddedResource Remove="Views\Templates\**" />
		<MauiCss Remove="Models\Base\**" />
		<MauiCss Remove="Views\Templates\**" />
		<MauiXaml Remove="Models\Base\**" />
		<MauiXaml Remove="Views\Templates\**" />
		<None Remove="Models\Base\**" />
		<None Remove="Views\Templates\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Fonts\FontAwesome6FreeBrands.otf" />
		<None Remove="Resources\Fonts\FontAwesome6FreeRegular.otf" />
		<None Remove="Resources\Fonts\FontAwesome6FreeSolid.otf" />
		<None Remove="Resources\Images\archives.svg" />
		<None Remove="Resources\Images\facebook2019.svg" />
		<None Remove="Resources\Images\google.svg" />
		<None Remove="Resources\Images\microsoft.svg" />
		<None Remove="Resources\Images\nutrition_plan.svg" />
		<None Remove="Resources\Images\trending_fire.png" />
		<None Remove="Resources\Images\tutorial2.jpg" />
		<None Remove="Resources\Images\tutorial_background.jpg" />
		<None Remove="Resources\Images\web_view.svg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="akgul.Maui.DataGrid" Version="3.0.0" />
		<PackageReference Include="CardsView.Maui" Version="0.0.4" />
		<PackageReference Include="CommunityToolkit.Maui" Version="7.0.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="FFImageLoadingCompat.Maui" Version="0.1.1" />
		<PackageReference Include="FirebaseDatabase.net" Version="4.2.0" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc1" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.54" />
		<PackageReference Include="Microcharts.Maui" Version="1.0.0" />
		<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.3" />
		<PackageReference Include="Mopups" Version="1.2.0" />
		<PackageReference Include="Sharpnado.Tabs.Maui" Version="3.0.1" />
		<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.7" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.7" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.7" />
		<PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.7" />
		<PackageReference Include="UraniumUI.Blurs" Version="2.7.2" />
		<!--<PackageReference Include="UraniumUI.Material" Version="2.7.2" />-->
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="ChatGptNet" Version="2.6.3" />
		<PackageReference Include="The49.Maui.BottomSheet" Version="1.0.4" />
		<!--<PackageReference Include="Firebase.Auth" Version="1.0.0" />-->
		<!--<PackageReference Include="FirebaseAuthentication.net" Version="4.0.2" />-->
	</ItemGroup>
	<!--<ItemGroup>
	  <ProjectReference Include="..\VeganLifeDataCenter\VeganLifeDataCenter.csproj" />
	</ItemGroup>-->
	<!--<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.5-beta1.23270.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MvvmCross.CodeAnalysis" Version="8.0.2" />
	</ItemGroup>-->

	<ItemGroup>
		<Compile Update="Resources\Translations\AppResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AppResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Views\BookmarkPage.xaml.cs">
			<DependentUpon>BookmarkPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\NavBarControl.xaml.cs">
			<DependentUpon>NavBarControl.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\Tabs\MacrosPage.xaml.cs">
			<DependentUpon>MacrosPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\Controls\Tabs\MacrosPage.xaml.cs">
			<DependentUpon>MacrosPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="Views\ToolFlyout\MainTool.xaml.cs">
			<DependentUpon>MainTool.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Translations\AppResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>AppResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<MauiXaml Update="Views\ContentViews\DataGridNutritionFactCW.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\DetailUsdaSpecBottomSheet.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NutritionFactImportantBorder.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Flyout\ToolFlyout\BMRCalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\BookmarkPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Flyout\ToolFlyout\BMICalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\ElementFoodDetailCW.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\RationPlanPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\CaloriesTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\MacrosTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\Tabs\NutrientsTab.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ContentViews\VitaminAndMineralPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\FlyoutHeader.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NavBarControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\NavBarRootPageControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\Tabs\CaloriesPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Controls\Tabs\MacrosPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\DetailVitaminAndMineralPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\FoodTab\FoodDetailPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\FoodTab\FoodsByCategoryPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\NewsFeedPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\AboutAppPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\BmiMoreInfoToolBarPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\BmiResultPopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\Popups\ProfilePopup.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\PortionTab\UsdaFoodFactDetailPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ProfilePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\RegistrationPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ReportPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SettingPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\SettingTab\LicensePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\ToolFlyout\BMICalculatorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\WebViewPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\WelcomePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>
</Project>
