//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeganLife.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeganLife.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string age_bmiPage {
            get {
                return ResourceManager.GetString("age_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the application to collect crash.
        ///Application logs are used to collect and analyze information for quality improvement, product development, and service improvement purposes..
        /// </summary>
        internal static string Alert_CollectOperationLogsPermission_Message {
            get {
                return ResourceManager.GetString("Alert_CollectOperationLogsPermission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with .
        /// </summary>
        internal static string app_allow {
            get {
                return ResourceManager.GetString("app_allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string app_common_bookmarkTab {
            get {
                return ResourceManager.GetString("app_common_bookmarkTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string app_common_homeTab {
            get {
                return ResourceManager.GetString("app_common_homeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portion.
        /// </summary>
        internal static string app_common_portionTab {
            get {
                return ResourceManager.GetString("app_common_portionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string app_common_searchTab {
            get {
                return ResourceManager.GetString("app_common_searchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string app_common_settingTab {
            get {
                return ResourceManager.GetString("app_common_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string app_common_toolsTab {
            get {
                return ResourceManager.GetString("app_common_toolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamins.
        /// </summary>
        internal static string app_common_vitaminsTab {
            get {
                return ResourceManager.GetString("app_common_vitaminsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        internal static string app_common_webViewTab {
            get {
                return ResourceManager.GetString("app_common_webViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leafy Lifestyle is an application about vegetarian recipes, bringing vegetarian values closer to you..
        /// </summary>
        internal static string app_detail {
            get {
                return ResourceManager.GetString("app_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leafy Lifestyle.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy..
        /// </summary>
        internal static string app_PrivacyPolicy {
            get {
                return ResourceManager.GetString("app_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live a healthy life,
        ///taste the whole moment.
        /// </summary>
        internal static string app_slogan {
            get {
                return ResourceManager.GetString("app_slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions..
        /// </summary>
        internal static string app_TermsAndConditions {
            get {
                return ResourceManager.GetString("app_TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        internal static string appSet_dateTime_1h_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1h_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        internal static string appSet_dateTime_1m_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1m_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        internal static string appSet_dateTime_1Month_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1Month_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        internal static string appSet_dateTime_1s_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1s_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days ago.
        /// </summary>
        internal static string appSet_dateTime_days_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours ago.
        /// </summary>
        internal static string appSet_dateTime_manyH_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyH_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes ago.
        /// </summary>
        internal static string appSet_dateTime_manyM_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyM_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds ago.
        /// </summary>
        internal static string appSet_dateTime_manyS_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyS_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  months ago.
        /// </summary>
        internal static string appSet_dateTime_months_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string appSet_dateTime_yesterday_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_yesterday_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        internal static string appVersion_settingPage {
            get {
                return ResourceManager.GetString("appVersion_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string breakfast_rationPlantPage {
            get {
                return ResourceManager.GetString("breakfast_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculate_bmiPage {
            get {
                return ResourceManager.GetString("calculate_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories content: .
        /// </summary>
        internal static string caloriesContent_foodDetailPage {
            get {
                return ResourceManager.GetString("caloriesContent_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel_common {
            get {
                return ResourceManager.GetString("cancel_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close_common {
            get {
                return ResourceManager.GetString("close_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow collect logs.
        /// </summary>
        internal static string collectLog_settingPage {
            get {
                return ResourceManager.GetString("collectLog_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark_settingPage {
            get {
                return ResourceManager.GetString("dark_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string darkMode_option_settingTab {
            get {
                return ResourceManager.GetString("darkMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorate.
        /// </summary>
        internal static string decorate_foodDetailPage {
            get {
                return ResourceManager.GetString("decorate_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are operating anonymously, fill in the information for a better experience.
        /// </summary>
        internal static string description_flyoutHeader {
            get {
                return ResourceManager.GetString("description_flyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string dinner_rationPlantPage {
            get {
                return ResourceManager.GetString("dinner_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        internal static string emptyName_profilePopupEdit {
            get {
                return ResourceManager.GetString("emptyName_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is empty!.
        /// </summary>
        internal static string emptyWeight_profilePopupEdit {
            get {
                return ResourceManager.GetString("emptyWeight_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        internal static string enterSearchTerm_Placeholder_shell {
            get {
                return ResourceManager.GetString("enterSearchTerm_Placeholder_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string explore_common {
            get {
                return ResourceManager.GetString("explore_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature under development.
        /// </summary>
        internal static string featureFunction_common {
            get {
                return ResourceManager.GetString("featureFunction_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female_bmiPage {
            get {
                return ResourceManager.GetString("female_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        internal static string healthy_feedPage {
            get {
                return ResourceManager.GetString("healthy_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hegiht.
        /// </summary>
        internal static string height_bmiPage {
            get {
                return ResourceManager.GetString("height_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incognito.
        /// </summary>
        internal static string incognito_flyoutHeader {
            get {
                return ResourceManager.GetString("incognito_flyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information saved successfully.
        /// </summary>
        internal static string infoAlert_userDataSaved_profilePopupEdit {
            get {
                return ResourceManager.GetString("infoAlert_userDataSaved_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string ingredient_foodDetailPage {
            get {
                return ResourceManager.GetString("ingredient_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối với trẻ em và thanh thiếu niên trong khoảng độ tuổi này, chỉ số BMI được tính toán theo cách sau:
        ///Dưới 5th: Gầy (Underweight) nếu BMI &lt; 5th percentile.
        ///5th - 84th percentile: Bình thường (Normal weight) nếu BMI nằm trong khoảng này.
        ///85th - 94th percentile: Thừa cân (Overweight) nếu BMI nằm trong khoảng này.
        ///95th percentile trở lên: Béo phì (Obese) nếu BMI ≥ 95th percentile..
        /// </summary>
        internal static string lessThan20_notFound_toolFlyout {
            get {
                return ResourceManager.GetString("lessThan20_notFound_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        internal static string lessThan5_notFound_toolFlyout {
            get {
                return ResourceManager.GetString("lessThan5_notFound_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string license_settingPage {
            get {
                return ResourceManager.GetString("license_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string license_technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("license_technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light_settingPage {
            get {
                return ResourceManager.GetString("light_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string lightMode_option_settingTab {
            get {
                return ResourceManager.GetString("lightMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string liveStrong_feedPage {
            get {
                return ResourceManager.GetString("liveStrong_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string lunch_rationPlantPage {
            get {
                return ResourceManager.GetString("lunch_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string making_foodDetailPage {
            get {
                return ResourceManager.GetString("making_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male_bmiPage {
            get {
                return ResourceManager.GetString("male_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều hướng thất bại!.
        /// </summary>
        internal static string navigationFailed_alert_common {
            get {
                return ResourceManager.GetString("navigationFailed_alert_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information about {0} dishes.
        ///List is empty!.
        /// </summary>
        internal static string noFoods_foodByCategoryDetailPage {
            get {
                return ResourceManager.GetString("noFoods_foodByCategoryDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string normal_toolFlyout {
            get {
                return ResourceManager.GetString("normal_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string note_foodDetailPage {
            get {
                return ResourceManager.GetString("note_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information on vitamins &amp; minerals.
        ///List is empty!.
        /// </summary>
        internal static string noVitamin_vitaminPage {
            get {
                return ResourceManager.GetString("noVitamin_vitaminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok_common {
            get {
                return ResourceManager.GetString("ok_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options_settingPage {
            get {
                return ResourceManager.GetString("options_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options setting.
        /// </summary>
        internal static string optionTitle_settingTab {
            get {
                return ResourceManager.GetString("optionTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m {0}, {1} years old, bmi index is {2}. Give me advice.
        /// </summary>
        internal static string queryBMI_bmiPopup {
            get {
                return ResourceManager.GetString("queryBMI_bmiPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string religion_feedPage {
            get {
                return ResourceManager.GetString("religion_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauce.
        /// </summary>
        internal static string sauce_foodDetailPage {
            get {
                return ResourceManager.GetString("sauce_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search anything!.
        /// </summary>
        internal static string searchPlace_mainPage {
            get {
                return ResourceManager.GetString("searchPlace_mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string sex_bmiPage {
            get {
                return ResourceManager.GetString("sex_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string sexDetail_content_bmiCalculatePage {
            get {
                return ResourceManager.GetString("sexDetail_content_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side meal.
        /// </summary>
        internal static string sideMeal_rationPlantPage {
            get {
                return ResourceManager.GetString("sideMeal_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Info.
        /// </summary>
        internal static string technicalInfo_settingPage {
            get {
                return ResourceManager.GetString("technicalInfo_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical info.
        /// </summary>
        internal static string technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body mass index.
        /// </summary>
        internal static string title_bmiCalculatePage {
            get {
                return ResourceManager.GetString("title_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BMI.
        /// </summary>
        internal static string title_bmiPopup {
            get {
                return ResourceManager.GetString("title_bmiPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal metabolic rate.
        /// </summary>
        internal static string title_bmrCalculatePage {
            get {
                return ResourceManager.GetString("title_bmrCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string underweight_toolFlyout {
            get {
                return ResourceManager.GetString("underweight_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan food.
        /// </summary>
        internal static string veganFood_feedPage {
            get {
                return ResourceManager.GetString("veganFood_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string weight_bmiPage {
            get {
                return ResourceManager.GetString("weight_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasing age is too old, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongAge_tooHigh_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongAge_tooHigh_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is too young, not yet supported
        ///	Re-enter.
        /// </summary>
        internal static string wrongAge_tooLow_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongAge_tooLow_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have entered weight wrong!.
        /// </summary>
        internal static string wrongWeight_profilePopupEdit {
            get {
                return ResourceManager.GetString("wrongWeight_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is too big, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongWeight_tooHigh_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongWeight_tooHigh_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is too low, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongWeight_tooLow_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongWeight_tooLow_bmiCalculatePage", resourceCulture);
            }
        }
    }
}
