//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeganLife.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeganLife.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string app_common_homeTab {
            get {
                return ResourceManager.GetString("app_common_homeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string app_common_searchTab {
            get {
                return ResourceManager.GetString("app_common_searchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string app_common_settingTab {
            get {
                return ResourceManager.GetString("app_common_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string darkMode_option_settingTab {
            get {
                return ResourceManager.GetString("darkMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string license_technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("license_technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string lightMode_option_settingTab {
            get {
                return ResourceManager.GetString("lightMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options setting.
        /// </summary>
        internal static string optionTitle_settingTab {
            get {
                return ResourceManager.GetString("optionTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical info.
        /// </summary>
        internal static string technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI Calculate.
        /// </summary>
        internal static string title_bmiCalculatePage {
            get {
                return ResourceManager.GetString("title_bmiCalculatePage", resourceCulture);
            }
        }
    }
}
