//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeganLife.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeganLife.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to affiliatePopup_productsRecommend_Title.
        /// </summary>
        internal static string affiliatePopup_productsRecommend_Title {
            get {
                return ResourceManager.GetString("affiliatePopup_productsRecommend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string age_bmiPage {
            get {
                return ResourceManager.GetString("age_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the application to collect crash.
        ///Application logs are used to collect and analyze information for quality improvement, product development, and service improvement purposes..
        /// </summary>
        internal static string Alert_CollectOperationLogsPermission_Message {
            get {
                return ResourceManager.GetString("Alert_CollectOperationLogsPermission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with .
        /// </summary>
        internal static string app_allow {
            get {
                return ResourceManager.GetString("app_allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_AthleticNutritionTab_Title.
        /// </summary>
        internal static string app_common_AthleticNutritionTab_Title {
            get {
                return ResourceManager.GetString("app_common_AthleticNutritionTab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string app_common_bookmarkTab {
            get {
                return ResourceManager.GetString("app_common_bookmarkTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_dataNote.
        /// </summary>
        internal static string app_common_dataNote {
            get {
                return ResourceManager.GetString("app_common_dataNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_encyclopediaTab.
        /// </summary>
        internal static string app_common_encyclopediaTab {
            get {
                return ResourceManager.GetString("app_common_encyclopediaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_gptUnableEx.
        /// </summary>
        internal static string app_common_gptUnableEx {
            get {
                return ResourceManager.GetString("app_common_gptUnableEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string app_common_homeTab {
            get {
                return ResourceManager.GetString("app_common_homeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_PharmacoLogical_Title.
        /// </summary>
        internal static string app_common_PharmacoLogical_Title {
            get {
                return ResourceManager.GetString("app_common_PharmacoLogical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portion.
        /// </summary>
        internal static string app_common_portionTab {
            get {
                return ResourceManager.GetString("app_common_portionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_common_recipeTab.
        /// </summary>
        internal static string app_common_recipeTab {
            get {
                return ResourceManager.GetString("app_common_recipeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string app_common_searchTab {
            get {
                return ResourceManager.GetString("app_common_searchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string app_common_settingTab {
            get {
                return ResourceManager.GetString("app_common_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string app_common_toolsTab {
            get {
                return ResourceManager.GetString("app_common_toolsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamins.
        /// </summary>
        internal static string app_common_vitaminsTab {
            get {
                return ResourceManager.GetString("app_common_vitaminsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        internal static string app_common_webViewTab {
            get {
                return ResourceManager.GetString("app_common_webViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leafy Lifestyle is an application about vegetarian recipes, bringing vegetarian values closer to you..
        /// </summary>
        internal static string app_detail {
            get {
                return ResourceManager.GetString("app_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HealthyChef.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy..
        /// </summary>
        internal static string app_PrivacyPolicy {
            get {
                return ResourceManager.GetString("app_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live a healthy life,
        ///taste the whole moment.
        /// </summary>
        internal static string app_slogan {
            get {
                return ResourceManager.GetString("app_slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions..
        /// </summary>
        internal static string app_TermsAndConditions {
            get {
                return ResourceManager.GetString("app_TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string app_title_report {
            get {
                return ResourceManager.GetString("app_title_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        internal static string appSet_dateTime_1h_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1h_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        internal static string appSet_dateTime_1m_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1m_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one month ago.
        /// </summary>
        internal static string appSet_dateTime_1Month_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1Month_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one second ago.
        /// </summary>
        internal static string appSet_dateTime_1s_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_1s_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days ago.
        /// </summary>
        internal static string appSet_dateTime_days_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours ago.
        /// </summary>
        internal static string appSet_dateTime_manyH_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyH_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes ago.
        /// </summary>
        internal static string appSet_dateTime_manyM_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyM_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds ago.
        /// </summary>
        internal static string appSet_dateTime_manyS_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_manyS_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  months ago.
        /// </summary>
        internal static string appSet_dateTime_months_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string appSet_dateTime_yesterday_ago {
            get {
                return ResourceManager.GetString("appSet_dateTime_yesterday_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        internal static string appVersion_settingPage {
            get {
                return ResourceManager.GetString("appVersion_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ash.
        /// </summary>
        internal static string Ash_common {
            get {
                return ResourceManager.GetString("Ash_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to askingAI_conversationChat.
        /// </summary>
        internal static string askingAI_conversationChat {
            get {
                return ResourceManager.GetString("askingAI_conversationChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string breakfast_rationPlantPage {
            get {
                return ResourceManager.GetString("breakfast_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        internal static string Calcium_common {
            get {
                return ResourceManager.GetString("Calcium_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculate_bmiPage {
            get {
                return ResourceManager.GetString("calculate_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories content: .
        /// </summary>
        internal static string caloriesContent_foodDetailPage {
            get {
                return ResourceManager.GetString("caloriesContent_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel_common {
            get {
                return ResourceManager.GetString("cancel_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantCollect_info_label.
        /// </summary>
        internal static string cantCollect_info_label {
            get {
                return ResourceManager.GetString("cantCollect_info_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cantFindBmiResult_bmiCalculatePage.
        /// </summary>
        internal static string cantFindBmiResult_bmiCalculatePage {
            get {
                return ResourceManager.GetString("cantFindBmiResult_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrate.
        /// </summary>
        internal static string Carbohydrate_common {
            get {
                return ResourceManager.GetString("Carbohydrate_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chatWithUs_supportPage.
        /// </summary>
        internal static string chatWithUs_supportPage {
            get {
                return ResourceManager.GetString("chatWithUs_supportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close_common {
            get {
                return ResourceManager.GetString("close_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow collect logs.
        /// </summary>
        internal static string collectLog_settingPage {
            get {
                return ResourceManager.GetString("collectLog_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        internal static string coming_soon {
            get {
                return ResourceManager.GetString("coming_soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cookingRecipe_mainPage.
        /// </summary>
        internal static string cookingRecipe_mainPage {
            get {
                return ResourceManager.GetString("cookingRecipe_mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        internal static string Copper_common {
            get {
                return ResourceManager.GetString("Copper_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark_settingPage {
            get {
                return ResourceManager.GetString("dark_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string darkMode_option_settingTab {
            get {
                return ResourceManager.GetString("darkMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string dateOfBirth_options_profilePopupEdit {
            get {
                return ResourceManager.GetString("dateOfBirth_options_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorate.
        /// </summary>
        internal static string decorate_foodDetailPage {
            get {
                return ResourceManager.GetString("decorate_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are operating anonymously, fill in the information for a better experience.
        /// </summary>
        internal static string description_flyoutHeader {
            get {
                return ResourceManager.GetString("description_flyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string dinner_rationPlantPage {
            get {
                return ResourceManager.GetString("dinner_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty list!.
        /// </summary>
        internal static string empty_list {
            get {
                return ResourceManager.GetString("empty_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t be afraid and ask us your question!.
        /// </summary>
        internal static string emptyChat_conversationChat {
            get {
                return ResourceManager.GetString("emptyChat_conversationChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is empty.
        /// </summary>
        internal static string emptyName_profilePopupEdit {
            get {
                return ResourceManager.GetString("emptyName_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is empty!.
        /// </summary>
        internal static string emptyWeight_profilePopupEdit {
            get {
                return ResourceManager.GetString("emptyWeight_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy_common {
            get {
                return ResourceManager.GetString("Energy_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        internal static string enterSearchTerm_Placeholder_shell {
            get {
                return ResourceManager.GetString("enterSearchTerm_Placeholder_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string explore_common {
            get {
                return ResourceManager.GetString("explore_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        internal static string Fat_common {
            get {
                return ResourceManager.GetString("Fat_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature under development.
        /// </summary>
        internal static string featureFunction_common {
            get {
                return ResourceManager.GetString("featureFunction_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string female_bmiPage {
            get {
                return ResourceManager.GetString("female_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        internal static string Fiber_common {
            get {
                return ResourceManager.GetString("Fiber_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill text here.
        /// </summary>
        internal static string fillText_placeHolder_macroTab {
            get {
                return ResourceManager.GetString("fillText_placeHolder_macroTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstQuery_athleticNutritionTab.
        /// </summary>
        internal static string firstQuery_athleticNutritionTab {
            get {
                return ResourceManager.GetString("firstQuery_athleticNutritionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstQuery_pharmacoLogicalTab.
        /// </summary>
        internal static string firstQuery_pharmacoLogicalTab {
            get {
                return ResourceManager.GetString("firstQuery_pharmacoLogicalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstQuery_vitaminPage.
        /// </summary>
        internal static string firstQuery_vitaminPage {
            get {
                return ResourceManager.GetString("firstQuery_vitaminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fructose.
        /// </summary>
        internal static string Fructose_common {
            get {
                return ResourceManager.GetString("Fructose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GaLactose.
        /// </summary>
        internal static string GaLactose_common {
            get {
                return ResourceManager.GetString("GaLactose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMorePoint_info_label.
        /// </summary>
        internal static string getMorePoint_info_label {
            get {
                return ResourceManager.GetString("getMorePoint_info_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        internal static string Glucose_common {
            get {
                return ResourceManager.GetString("Glucose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go list page.
        /// </summary>
        internal static string goList_bookmarkPage {
            get {
                return ResourceManager.GetString("goList_bookmarkPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        internal static string healthy_feedPage {
            get {
                return ResourceManager.GetString("healthy_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hegiht.
        /// </summary>
        internal static string height_bmiPage {
            get {
                return ResourceManager.GetString("height_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incognito.
        /// </summary>
        internal static string incognito_flyoutHeader {
            get {
                return ResourceManager.GetString("incognito_flyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information saved successfully.
        /// </summary>
        internal static string infoAlert_userDataSaved_profilePopupEdit {
            get {
                return ResourceManager.GetString("infoAlert_userDataSaved_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infor_common.
        /// </summary>
        internal static string Infor_common {
            get {
                return ResourceManager.GetString("Infor_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string ingredient_foodDetailPage {
            get {
                return ResourceManager.GetString("ingredient_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string Iron_common {
            get {
                return ResourceManager.GetString("Iron_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactose.
        /// </summary>
        internal static string Lactose_common {
            get {
                return ResourceManager.GetString("Lactose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi tới trang phân tích.
        /// </summary>
        internal static string lbSelectBtn_goNext_toolFlyout {
            get {
                return ResourceManager.GetString("lbSelectBtn_goNext_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        internal static string lbSelectBtn_reCalculate_toolFlyout {
            get {
                return ResourceManager.GetString("lbSelectBtn_reCalculate_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và đặt làm chỉ số phân tích mặc định.
        /// </summary>
        internal static string lbSelectBtn_save_toolFlyout {
            get {
                return ResourceManager.GetString("lbSelectBtn_save_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối với trẻ em và thanh thiếu niên trong khoảng độ tuổi này, chỉ số BMI được tính toán theo cách sau:
        ///Dưới 5th: Gầy (Underweight) nếu BMI &lt; 5th percentile.
        ///5th - 84th percentile: Bình thường (Normal weight) nếu BMI nằm trong khoảng này.
        ///85th - 94th percentile: Thừa cân (Overweight) nếu BMI nằm trong khoảng này.
        ///95th percentile trở lên: Béo phì (Obese) nếu BMI ≥ 95th percentile..
        /// </summary>
        internal static string lessThan20_notFound_toolFlyout {
            get {
                return ResourceManager.GetString("lessThan20_notFound_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found!.
        /// </summary>
        internal static string lessThan5_notFound_toolFlyout {
            get {
                return ResourceManager.GetString("lessThan5_notFound_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string license_settingPage {
            get {
                return ResourceManager.GetString("license_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string license_technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("license_technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light_settingPage {
            get {
                return ResourceManager.GetString("light_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string lightMode_option_settingTab {
            get {
                return ResourceManager.GetString("lightMode_option_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string liveStrong_feedPage {
            get {
                return ResourceManager.GetString("liveStrong_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string lunch_rationPlantPage {
            get {
                return ResourceManager.GetString("lunch_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        internal static string Magnesium_common {
            get {
                return ResourceManager.GetString("Magnesium_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking.
        /// </summary>
        internal static string making_foodDetailPage {
            get {
                return ResourceManager.GetString("making_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string male_bmiPage {
            get {
                return ResourceManager.GetString("male_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltose.
        /// </summary>
        internal static string Maltose_common {
            get {
                return ResourceManager.GetString("Maltose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_SuperActive.
        /// </summary>
        internal static string mealLogsPage_BMI_description {
            get {
                return ResourceManager.GetString("mealLogsPage_BMI_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_BMR_description.
        /// </summary>
        internal static string mealLogsPage_BMR_description {
            get {
                return ResourceManager.GetString("mealLogsPage_BMR_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_LightlyActive.
        /// </summary>
        internal static string mealLogsPage_LightlyActive {
            get {
                return ResourceManager.GetString("mealLogsPage_LightlyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_ModeratelyActive.
        /// </summary>
        internal static string mealLogsPage_ModeratelyActive {
            get {
                return ResourceManager.GetString("mealLogsPage_ModeratelyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_sedentary.
        /// </summary>
        internal static string mealLogsPage_sedentary {
            get {
                return ResourceManager.GetString("mealLogsPage_sedentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_SuperActive.
        /// </summary>
        internal static string mealLogsPage_SuperActive {
            get {
                return ResourceManager.GetString("mealLogsPage_SuperActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_TDEE_description.
        /// </summary>
        internal static string mealLogsPage_TDEE_description {
            get {
                return ResourceManager.GetString("mealLogsPage_TDEE_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mealLogsPage_VeryActive.
        /// </summary>
        internal static string mealLogsPage_VeryActive {
            get {
                return ResourceManager.GetString("mealLogsPage_VeryActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minerals.
        /// </summary>
        internal static string Minerals_common {
            get {
                return ResourceManager.GetString("Minerals_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu cân - Gầy.
        /// </summary>
        internal static string moderateThinness_classify_bmi {
            get {
                return ResourceManager.GetString("moderateThinness_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name_options_profilePopupEdit {
            get {
                return ResourceManager.GetString("name_options_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều hướng thất bại!.
        /// </summary>
        internal static string navigationFailed_alert_common {
            get {
                return ResourceManager.GetString("navigationFailed_alert_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next_welcomePage {
            get {
                return ResourceManager.GetString("next_welcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information about {0} dishes.
        ///List is empty!.
        /// </summary>
        internal static string noFoods_foodByCategoryDetailPage {
            get {
                return ResourceManager.GetString("noFoods_foodByCategoryDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bình thường.
        /// </summary>
        internal static string normal_classify_bmi {
            get {
                return ResourceManager.GetString("normal_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string normal_toolFlyout {
            get {
                return ResourceManager.GetString("normal_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string note_foodDetailPage {
            get {
                return ResourceManager.GetString("note_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information on vitamins &amp; minerals.
        ///List is empty!.
        /// </summary>
        internal static string noVitamin_vitaminPage {
            get {
                return ResourceManager.GetString("noVitamin_vitaminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutritions Fact.
        /// </summary>
        internal static string nutritionFact_foodDetail {
            get {
                return ResourceManager.GetString("nutritionFact_foodDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thừa cân.
        /// </summary>
        internal static string obese_classify_bmi {
            get {
                return ResourceManager.GetString("obese_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thừa cân - Béo phì độ 1.
        /// </summary>
        internal static string obese1_classify_bmi {
            get {
                return ResourceManager.GetString("obese1_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thừa cân - Béo phì độ 2.
        /// </summary>
        internal static string obese2_classify_bmi {
            get {
                return ResourceManager.GetString("obese2_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thừa cân - Béo phì độ 3.
        /// </summary>
        internal static string obese3_classify_bmi {
            get {
                return ResourceManager.GetString("obese3_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok_common {
            get {
                return ResourceManager.GetString("ok_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options_settingPage {
            get {
                return ResourceManager.GetString("options_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options setting.
        /// </summary>
        internal static string optionTitle_settingTab {
            get {
                return ResourceManager.GetString("optionTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus.
        /// </summary>
        internal static string Phosphorus_common {
            get {
                return ResourceManager.GetString("Phosphorus_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        internal static string Potassium_common {
            get {
                return ResourceManager.GetString("Potassium_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previous_welcomePage {
            get {
                return ResourceManager.GetString("previous_welcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào bạn {0}. Cùng xây dựng kế hoạch một cách đầy năng lượng và hứng khởi nhé!.
        /// </summary>
        internal static string prompt_greeting {
            get {
                return ResourceManager.GetString("prompt_greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào bạn {0}. Hôm nay là ngày hoàn hảo để nuôi dưỡng cơ thể và tâm hồn bạn với những bữa ăn ngon lành và bổ dưỡng.
        ///Hãy thưởng thức mỗi miếng ăn như một bước tiến vững chắc trên hành trình hướng tới sức khỏe và hạnh phúc! 💪🥗🌟.
        /// </summary>
        internal static string prompt_greeting_v1 {
            get {
                return ResourceManager.GetString("prompt_greeting_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        internal static string Protein_common {
            get {
                return ResourceManager.GetString("Protein_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximates.
        /// </summary>
        internal static string Proximates_common {
            get {
                return ResourceManager.GetString("Proximates_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m {0}, {1} years old, bmi index is {2}. Give me advice.
        /// </summary>
        internal static string queryBMI_bmiPopup {
            get {
                return ResourceManager.GetString("queryBMI_bmiPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string recipe_foodDetail {
            get {
                return ResourceManager.GetString("recipe_foodDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string religion_feedPage {
            get {
                return ResourceManager.GetString("religion_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  results.
        /// </summary>
        internal static string result_lb {
            get {
                return ResourceManager.GetString("result_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauce.
        /// </summary>
        internal static string sauce_foodDetailPage {
            get {
                return ResourceManager.GetString("sauce_foodDetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search anything!.
        /// </summary>
        internal static string searchPlace_mainPage {
            get {
                return ResourceManager.GetString("searchPlace_mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiecStop_common.
        /// </summary>
        internal static string ServiecStop_common {
            get {
                return ResourceManager.GetString("ServiecStop_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu cân - Rất gầy.
        /// </summary>
        internal static string severeThinness_classify_bmi {
            get {
                return ResourceManager.GetString("severeThinness_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string sex_bmiPage {
            get {
                return ResourceManager.GetString("sex_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string sex_options_profilePopupEdit {
            get {
                return ResourceManager.GetString("sex_options_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string sexDetail_content_bmiCalculatePage {
            get {
                return ResourceManager.GetString("sexDetail_content_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ với bạn bè.
        /// </summary>
        internal static string shareWithFriends_footer_shell {
            get {
                return ResourceManager.GetString("shareWithFriends_footer_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side meal.
        /// </summary>
        internal static string sideMeal_rationPlantPage {
            get {
                return ResourceManager.GetString("sideMeal_rationPlantPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string skip_welcomePage {
            get {
                return ResourceManager.GetString("skip_welcomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        internal static string Sodium_common {
            get {
                return ResourceManager.GetString("Sodium_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starch.
        /// </summary>
        internal static string Starch_common {
            get {
                return ResourceManager.GetString("Starch_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucrose.
        /// </summary>
        internal static string Sucrose_common {
            get {
                return ResourceManager.GetString("Sucrose_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars.
        /// </summary>
        internal static string Sugars_common {
            get {
                return ResourceManager.GetString("Sugars_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Info.
        /// </summary>
        internal static string technicalInfo_settingPage {
            get {
                return ResourceManager.GetString("technicalInfo_settingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical info.
        /// </summary>
        internal static string technicalTitle_settingTab {
            get {
                return ResourceManager.GetString("technicalTitle_settingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu cân.
        /// </summary>
        internal static string Thinness_classify_bmi {
            get {
                return ResourceManager.GetString("Thinness_classify_bmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body mass index.
        /// </summary>
        internal static string title_bmiCalculatePage {
            get {
                return ResourceManager.GetString("title_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BMI.
        /// </summary>
        internal static string title_bmiPopup {
            get {
                return ResourceManager.GetString("title_bmiPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basal metabolic rate.
        /// </summary>
        internal static string title_bmrCalculatePage {
            get {
                return ResourceManager.GetString("title_bmrCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACRO.
        /// </summary>
        internal static string title_macroTab {
            get {
                return ResourceManager.GetString("title_macroTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string title_profile_profilePopupEdit {
            get {
                return ResourceManager.GetString("title_profile_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title_supportPage.
        /// </summary>
        internal static string title_supportPage {
            get {
                return ResourceManager.GetString("title_supportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify: .
        /// </summary>
        internal static string titleClassify_toolFlyout {
            get {
                return ResourceManager.GetString("titleClassify_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string underweight_toolFlyout {
            get {
                return ResourceManager.GetString("underweight_toolFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegan food.
        /// </summary>
        internal static string veganFood_feedPage {
            get {
                return ResourceManager.GetString("veganFood_feedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waitingForCollect_info_label.
        /// </summary>
        internal static string waitingForCollect_info_label {
            get {
                return ResourceManager.GetString("waitingForCollect_info_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water_common {
            get {
                return ResourceManager.GetString("Water_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string weight_bmiPage {
            get {
                return ResourceManager.GetString("weight_bmiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasing age is too old, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongAge_tooHigh_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongAge_tooHigh_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is too young, not yet supported
        ///	Re-enter.
        /// </summary>
        internal static string wrongAge_tooLow_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongAge_tooLow_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have entered weight wrong!.
        /// </summary>
        internal static string wrongWeight_profilePopupEdit {
            get {
                return ResourceManager.GetString("wrongWeight_profilePopupEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is too big, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongWeight_tooHigh_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongWeight_tooHigh_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight is too low, you seem to have entered it wrong.
        /// </summary>
        internal static string wrongWeight_tooLow_bmiCalculatePage {
            get {
                return ResourceManager.GetString("wrongWeight_tooLow_bmiCalculatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zinc.
        /// </summary>
        internal static string Zinc_common {
            get {
                return ResourceManager.GetString("Zinc_common", resourceCulture);
            }
        }
    }
}
