// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeganLifeDataCenter.Data;

#nullable disable

namespace VeganLifeDataCenter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230912175530_InitialReportTable")]
    partial class InitialReportTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("VeganLifeDataCenter.Models.ReportModel", b =>
                {
                    b.Property<DateTimeOffset?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalKcal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentBreakfast")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentDinner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentLunch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentOther")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.ToTable("ReportModels");
                });
#pragma warning restore 612, 618
        }
    }
}
